export const categories = [
  {
    id: 1,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
  {
    id: 2,
    name: "Drinks",
    image: require("../assets/images/sodaCategories.png"),
  },
  {
    id: 3,
    name: "Snacks",
    image: require("../assets/images/snackCategories.png"),
  },
  {
    id: 4,
    name: "Candy",
    image: require("../assets/images/candyCategories.png"),
  },
  {
    id: 5,
    name: "Pizza",
    image: require("../assets/images/pizzaCategories.png"),
  },
  {
    id: 6,
    name: "Mexican",
    image: require("../assets/images/tacoCategories.png"),
  },
];

export const featured = {
  id: 1,
  title: "The Best Restaurants",
  description: "Best Dishes Food in the City",
  restaurants: [
    {
      id: 1,
      name: "Sell Burguer",
      image: require("../assets/images/hamburguer.jpg"),
      description: "Hamburger beef and chicken",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "Santa Rosa de Lima",
      stars: 3,
      reviews: "3k",
      category: "Hamburgers",
      dishes: [
        {
          id: 1,
          name: "Baby Burguers",
          description: "Beef Burguer",
          price: 12.5,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 2,
          name: "Classic Chiken Burguer",
          description: "Chicken Burguer",
          price: 10,
          image: require("../assets/images/chickenBurguer.jpg"),
        },
        {
          id: 3,
          name: "Vegan Burguer",
          description: "The best vegan burguer",
          price: 6,
          image: require("../assets/images/veganBurguer.jpg"),
        },
      ],
    },
    {
      id: 2,
      name: "Pizza Little Caesars",
      image: require("../assets/images/littleCaesars.png"),
      description: "Pizza Pizza",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "San  Miguel",
      stars: 4.5,
      reviews: "4.5k",
      category: "Pizza",
      dishes: [
        {
          id: 1,
          name: "Crazy Bread",
          description: "Palitos de Pan",
          price: 3.25,
          image: require("../assets/images/crazyBread.jpg"),
        },
        {
          id: 2,
          name: "Supreme Pizza",
          description: "Pizza with vegetables",
          price: 8.95,
          image: require("../assets/images/ultimateSupremePizza.jpg"),
        },
        {
          id: 3,
          name: "Coca-Cola",
          description: "Soda 1.5 litros",
          price: 1.25,
          image: require("../assets/images/drinkLittleCaesars.jpeg"),
        },
      ],
    },
    {
      id: 3,
      name: "LacaLaca",
      image: require("../assets/images/lacalacaLogo.jpg"),
      description: "The best Tacos and Tortas",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "San Salvador",
      stars: 5,
      reviews: "5k",
      category: "Mexican Food",
      dishes: [
        {
          id: 1,
          name: "Laca BreakFast",
          description: "Combo Laca Love Breakfast",
          price: 2.75,
          image: require("../assets/images/breakfastLacaLove.jpeg"),
        },
        {
          id: 2,
          name: "Mini Chilachos",
          description: "Mexican Nachos with beans and chirimol",
          price: 6.99,
          image: require("../assets/images/miniChilachosLacaLaca.jpeg"),
        },
        {
          id: 3,
          name: "Costra Laca",
          description: "Costra Laca with chedar chesse",
          price: 5.99,
          image: require("../assets/images/costraLacaLaca.jpeg"),
        },
      ],
    },
  ],
};
