export const categories = [
  {
    id: 1,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
  {
    id: 2,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
  {
    id: 3,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
  {
    id: 4,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
  {
    id: 5,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
  {
    id: 6,
    name: "Hambuger",
    image: require("../assets/images/hamburguerIcon.png"),
  },
];

export const featured = {
  id: 1,
  title: "The Best Hamburguer",
  description: "beef or chicken",
  restaurants: [
    {
      id: 1,
      name: "Sell Burguer",
      image: require("../assets/images/hamburguer.jpg"),
      description: "grilled meat with caramelized onion",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "San  Miguel",
      stars: 4,
      reviews: "5k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 2,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 3,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
      ],
    },
    {
      id: 2,
      name: "Sell Burguer",
      image: require("../assets/images/hamburguer.jpg"),
      description: "grilled meat with caramelized onion",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "San  Miguel",
      stars: 4,
      reviews: "5k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 2,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 3,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
      ],
    },
    {
      id: 3,
      name: "Sell Burguer",
      image: require("../assets/images/hamburguer.jpg"),
      description: "grilled meat with caramelized onion",
      lng: -85.5324269,
      lat: 38.2145602,
      address: "San  Miguel",
      stars: 4,
      reviews: "5k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 2,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
        {
          id: 3,
          name: "Baby hamburgers",
          description: "Beef or chicken burger",
          price: 10,
          image: require("../assets/images/hamburgerDish.jpg"),
        },
      ],
    },
  ],
};
